include:
  - defaults.apt
  - defaults.configs
  - defaults.env
  - defaults.havegeds
  - defaults.hosts
  - defaults.network
  - defaults.packages
  - defaults.rkhunter
  - defaults.sudo
  - defaults.vim
